apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-jicofo
  namespace: {{ .Values.namespace }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jitsi-jicofo
  template:
    metadata:
      labels:
        app: jitsi-jicofo
    spec:
      nodeSelector:
        role: hub
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: jicofo
          image: jitsi/jicofo:{{ .Values.imageTag }}
          env:
            - name: AUTH_TYPE
              value: internal
            - name: ENABLE_AUTH
              value: "0"
            - name: XMPP_DOMAIN
              value: {{ .Values.xmpp.domain }}
            - name: XMPP_AUTH_DOMAIN
              value: {{ .Values.xmpp.authDomain }}
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: {{ .Values.xmpp.internalMucDomain }}
            - name: XMPP_SERVER
              value: prosody
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: {{ .Values.timezone }}
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: jicofo-component-secret
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: jicofo-auth-password
          resources:
            requests:
              cpu: {{ .Values.jicofo.resources.requests.cpu }}
              memory: {{ .Values.jicofo.resources.requests.memory }}
            limits:
              cpu: {{ .Values.jicofo.resources.limits.cpu }}
              memory: {{ .Values.jicofo.resources.limits.memory }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
