apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "http://30.0.0.1:8200"
      path: "infra"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: antlers
          key: token
