all:
  children:
    hub_de:
      hosts:
        fornex-de-frankfurt-happyfaraday:
          ansible_host: 31.172.71.140
    hub_us:
      hosts:
        aeza-us-charlotte-youngrose:
          ansible_host: 193.233.130.62
    gate:
      hosts:
        fornex-ru-moscow-hungrykapitsa:
          ansible_host: 81.85.78.139
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/infra_key
