[Interface]
PrivateKey = VAULT_MANAGED
Table = off
Address = 172.16.0.2/32
MTU = 1280

PostUp = ip rule add from 172.16.0.2 lookup warp
PostUp = ip rule add from 10.0.0.0/24 lookup warp
PostUp = ip route add default dev awg3 table warp

PostDown = ip rule del from 172.16.0.2 lookup warp
PostDown = ip rule del from 10.0.0.0/24 lookup warp
PostDown = ip route del default dev awg3 table warp

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
Endpoint = 162.159.192.1:2408
#Endpoint = engage.cloudflareclient.com:2408
PersistentKeepalive = 25