apiVersion: v1
kind: ConfigMap
metadata:
  name: warp-proxy-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    error_log /dev/stderr warn;
    events {}
    stream {
        resolver 8.8.8.8 valid=30s ipv6=off;
        error_log /dev/stderr warn;
        server {
            listen {{ .Values.listenAddr }}:443;
            ssl_preread on;
            proxy_bind {{ .Values.bindAddr }};
            proxy_pass $ssl_preread_server_name:443;
        }
    }
