apiVersion: v1
kind: ConfigMap
metadata:
  name: warp-proxy-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    error_log /dev/stderr warn;
    events {}
    stream {
        map $ssl_preread_server_name $warp_backend {
            aistudio.google.com                         aistudio.google.com:443;
            gemini.google.com                           gemini.google.com:443;
            alkalimakersuite-pa.clients6.google.com     alkalimakersuite-pa.clients6.google.com:443;
            developerprofiles-pa.googleapis.com         developerprofiles-pa.googleapis.com:443;
            notebooklm.google                           notebooklm.google:443;
            notebooklm.google.com                       notebooklm.google.com:443;
            proactivebackend-pa.googleapis.com          proactivebackend-pa.googleapis.com:443;
            generativelanguage.googleapis.com           generativelanguage.googleapis.com:443;
            instagram.com                               instagram.com:443;
            www.instagram.com                           www.instagram.com:443;
            i.instagram.com                             i.instagram.com:443;
            graph.instagram.com                         graph.instagram.com:443;
            cdninstagram.com                            cdninstagram.com:443;
            fbcdn.net                                   fbcdn.net:443;
        }
        server {
            listen 30.0.0.1:443;
            proxy_pass $warp_backend;
            proxy_bind 172.16.0.2;
            resolver 1.1.1.1 valid=300s ipv6=off;
            ssl_preread on;
        }
    }
