apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-proxy
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: warp-proxy
  template:
    metadata:
      labels:
        app: warp-proxy
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeHostname }}
      hostNetwork: true
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: warp-proxy-config
