[Interface]
Address = 30.0.0.3/24
ListenPort = 51821
PrivateKey = VAULT_MANAGED
Jc = 6
Jmin = 8
Jmax = 80
S1 = 21
S2 = 126
H1 = 664839111
H2 = 1485638111
H3 = 1457145111
H4 = 1956374111
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -I FORWARD 1 -i %i -o enp0s3 -j ACCEPT --wait 10
PostUp = iptables -I FORWARD 2 -i enp0s3 -o %i -j ACCEPT --wait 10
PostUp = iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE --wait 10
PostDown = iptables -D FORWARD -i %i -o enp0s3 -j ACCEPT --wait 10
PostDown = iptables -D FORWARD -i enp0s3 -o %i -j ACCEPT --wait 10
PostDown = iptables -t nat -D POSTROUTING -o enp0s3 -j MASQUERADE --wait 10

[Peer] # RU-1 (Gate awg2)
PublicKey = ITo1nuAGZ/9I7na18t6l/ylJ37JNSvGkFt6ebwNm9nM=
AllowedIPs = 30.0.0.4/32, 10.2.0.0/24
PersistentKeepalive = 25
