apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-synapse-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: matrix-synapse-secret
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.synapse.secret.vaultPath }}
        property: postgres_password
    - secretKey: registration-shared-secret
      remoteRef:
        key: {{ .Values.synapse.secret.vaultPath }}
        property: registration_shared_secret
    - secretKey: macaroon-secret-key
      remoteRef:
        key: {{ .Values.synapse.secret.vaultPath }}
        property: macaroon_secret_key
    - secretKey: form-secret
      remoteRef:
        key: {{ .Values.synapse.secret.vaultPath }}
        property: form_secret
