apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.matrixHost }}
        - {{ .Values.ingress.elementHost }}
      secretName: matrix-tls
  rules:
    - host: {{ .Values.ingress.matrixHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse
                port:
                  number: 8008
    - host: {{ .Values.ingress.elementHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: element
                port:
                  number: 80
