namespace: prod

image:
  repository: antonk44/quiz-core-svc
  tag: latest

nodeSelector:
  role: hub

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env:
  datasourceUrl: "jdbc:postgresql://shared-postgres:5432/quiz_core"
  datasourceUsername: "quiz_core"
  kafkaBootstrapServers: "kafka:9092"

externalSecret:
  refreshInterval: "1h"
  vaultPath: services/quiz-core

ingress:
  host: ""
