apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        monitoring-manager: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}
          args:
            - '--config.file=/etc/prometheus/prometheus.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time={{ .Values.prometheus.retention }}'
          ports:
            - containerPort: {{ .Values.prometheus.service.port }}
          resources:
            requests:
              cpu: {{ .Values.prometheus.resources.requests.cpu }}
              memory: {{ .Values.prometheus.resources.requests.memory }}
            limits:
              cpu: {{ .Values.prometheus.resources.limits.cpu }}
              memory: {{ .Values.prometheus.resources.limits.memory }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data
