- name: Configure hub server
  hosts: hub_de
  roles:
    - common/docker
    - nginx
    - amneziawg
    - services/vault
    - services/monitoring/prometheus
    - services/monitoring/grafana
    - services/monitoring/node-exporter