apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jitsi-prosody
  ports:
    - name: xmpp-client
      port: 5222
      targetPort: 5222
    - name: xmpp-component
      port: 5347
      targetPort: 5347
    - name: bosh
      port: 5280
      targetPort: 5280
