[Interface]
Address = 30.0.0.2/24
PrivateKey = VAULT_MANAGED
Table = off

Jc = 6
Jmin = 8
Jmax = 80
S1 = 21
S2 = 126
H1 = 664839111
H2 = 1485638111
H3 = 1457145111
H4 = 1956374111

PostUp = ip route add 30.0.0.1/32 dev awg1 table wgshared
PostUp = ip route add 30.0.0.1/32 dev awg1
PostUp = iptables -t nat -A POSTROUTING -s 10.2.0.0/24 -o awg1 -j MASQUERADE
PostDown = ip route del 30.0.0.1/32 dev awg1 table wgshared
PostDown = ip route del 30.0.0.1/32 dev awg1
PostDown = iptables -t nat -D POSTROUTING -s 10.2.0.0/24 -o awg1 -j MASQUERADE

[Peer]
PublicKey = oAIW/xgDzn5YVoFYkXn5exq5VOlT3y/BlGqskmG0EhQ=
Endpoint = 31.172.71.140:51821
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
