[Interface]
Address = 30.0.0.4/24
PrivateKey = VAULT_MANAGED
Table = off

Jc = 6
Jmin = 8
Jmax = 80
S1 = 21
S2 = 126
H1 = 664839111
H2 = 1485638111
H3 = 1457145111
H4 = 1956374111

PostUp = ip route add 30.0.0.3/32 dev awg2 table wgshared
PostUp = ip route add 30.0.0.3/32 dev awg2
PostUp = iptables -t nat -A POSTROUTING -s 10.2.0.0/24 -o awg2 -j MASQUERADE
PostDown = ip route del 30.0.0.3/32 dev awg2 table wgshared
PostDown = ip route del 30.0.0.3/32 dev awg2
PostDown = iptables -t nat -D POSTROUTING -s 10.2.0.0/24 -o awg2 -j MASQUERADE

[Peer] # US-1 (Hub USA)
PublicKey = sWmbDKI408iae/W12LfxOklWCQfIv8UeBaKNzxwghmI=
Endpoint = 193.233.130.62:51821
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
