apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-srv
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.srv }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.db }}
