apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-synapse-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.synapse.storage.size }}
