apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stepik-adapter-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: stepik-adapter-secret
  data:
    - secretKey: telegram-bot-token
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: telegram-bot-token
    - secretKey: telegram-bot-username
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: telegram-bot-username
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db-password
