apiVersion: v1
kind: Service
metadata:
  name: jitsi-web
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jitsi-web
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
