apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.namespace }}
data:
  vault.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = true
    }

    storage "raft" {
      path = "/vault/data"
      node_id = "main-vault-0"
    }

    seal "transit" {
      address = "http://127.0.0.1:8100"
      disable_renewal = false
      key_name = "main-vault-unseal"
      mount_path = "transit/"
    }

    api_addr = "{{ .Values.apiAddr }}"
    cluster_addr = "{{ .Values.clusterAddr }}"
