apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
