apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quiz-core-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: quiz-core-secret
  data:
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_password
    - secretKey: api-key-encryption-secret
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: api_key_encryption_secret
