apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-core-svc
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quiz-core-svc
                port:
                  number: 80
