apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "{{ .Values.vault.server }}"
      path: "{{ .Values.vault.path }}"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecret }}
          namespace: {{ .Values.namespace }}
          key: {{ .Values.vault.tokenKey }}
